{
  "proc": "http",
  "stages": {
    "subctx_split": {
      "count": 2947,
      "total_ms": 1254.7966,
      "mean_us": 425.788,
      "max_us": 4242.885
    },
    "tpl_render": {
      "count": 2946,
      "total_ms": 6667.0971,
      "mean_us": 2263.102,
      "max_us": 10365.305
    }
  },
  "measured": {
    "subctx_split": {
      "count": 2944,
      "total_ms": 1254.4917,
      "mean_us": 426.118,
      "max_us": 4242.885
    },
    "tpl_render": {
      "count": 2943,
      "total_ms": 6665.8641,
      "mean_us": 2264.99,
      "max_us": 10365.305
    }
  }
}