{
  "proc": "http",
  "stages": {
    "subctx_split": {
      "count": 53,
      "total_ms": 34.5962,
      "mean_us": 652.758,
      "max_us": 989.556
    },
    "tpl_render": {
      "count": 52,
      "total_ms": 685.6459,
      "mean_us": 13185.497,
      "max_us": 26507.611
    }
  },
  "measured": {
    "subctx_split": {
      "count": 50,
      "total_ms": 34.3246,
      "mean_us": 686.492,
      "max_us": 989.556
    },
    "tpl_render": {
      "count": 49,
      "total_ms": 684.4688,
      "mean_us": 13968.752,
      "max_us": 26507.611
    }
  }
}