{
  "proc": "http",
  "stages": {
    "subctx_split": {
      "count": 2439,
      "total_ms": 1284.6908,
      "mean_us": 526.728,
      "max_us": 2319.409
    },
    "tpl_render": {
      "count": 2438,
      "total_ms": 6291.0441,
      "mean_us": 2580.412,
      "max_us": 10308.875
    }
  },
  "measured": {
    "subctx_split": {
      "count": 2436,
      "total_ms": 1284.4138,
      "mean_us": 527.263,
      "max_us": 2319.409
    },
    "tpl_render": {
      "count": 2435,
      "total_ms": 6289.7838,
      "mean_us": 2583.073,
      "max_us": 10308.875
    }
  }
}