{
  "proc": "http",
  "stages": {
    "subctx_split": {
      "count": 792,
      "total_ms": 0.9027,
      "mean_us": 1.14,
      "max_us": 25.544
    },
    "tpl_render": {
      "count": 791,
      "total_ms": 757.2731,
      "mean_us": 957.362,
      "max_us": 6886.113
    }
  },
  "measured": {
    "subctx_split": {
      "count": 789,
      "total_ms": 0.8984,
      "mean_us": 1.139,
      "max_us": 25.544
    },
    "tpl_render": {
      "count": 788,
      "total_ms": 756.3944,
      "mean_us": 959.891,
      "max_us": 6886.113
    }
  }
}