{
  "proc": "http",
  "stages": {
    "subctx_split": {
      "count": 2947,
      "total_ms": 3.7088,
      "mean_us": 1.258,
      "max_us": 25.555
    },
    "tpl_render": {
      "count": 2946,
      "total_ms": 5437.4111,
      "mean_us": 1845.693,
      "max_us": 9456.689
    }
  },
  "measured": {
    "subctx_split": {
      "count": 2944,
      "total_ms": 3.705,
      "mean_us": 1.258,
      "max_us": 25.555
    },
    "tpl_render": {
      "count": 2943,
      "total_ms": 5436.4109,
      "mean_us": 1847.234,
      "max_us": 9456.689
    }
  }
}