{
  "proc": "http",
  "stages": {
    "subctx_split": {
      "count": 53,
      "total_ms": 0.0925,
      "mean_us": 1.746,
      "max_us": 2.699
    },
    "tpl_render": {
      "count": 52,
      "total_ms": 633.6002,
      "mean_us": 12184.619,
      "max_us": 20126.351
    }
  },
  "measured": {
    "subctx_split": {
      "count": 50,
      "total_ms": 0.0879,
      "mean_us": 1.758,
      "max_us": 2.699
    },
    "tpl_render": {
      "count": 49,
      "total_ms": 632.6432,
      "mean_us": 12911.085,
      "max_us": 20126.351
    }
  }
}