{
  "proc": "http",
  "stages": {
    "subctx_split": {
      "count": 27,
      "total_ms": 0.0394,
      "mean_us": 1.461,
      "max_us": 2.677
    },
    "tpl_render": {
      "count": 26,
      "total_ms": 42.5636,
      "mean_us": 1637.062,
      "max_us": 2936.002
    }
  },
  "measured": {
    "subctx_split": {
      "count": 24,
      "total_ms": 0.0329,
      "mean_us": 1.371,
      "max_us": 2.347
    },
    "tpl_render": {
      "count": 23,
      "total_ms": 41.3379,
      "mean_us": 1797.301,
      "max_us": 2936.002
    }
  }
}