{
  "proc": "http",
  "stages": {
    "subctx_split": {
      "count": 2439,
      "total_ms": 2.9763,
      "mean_us": 1.22,
      "max_us": 4.527
    },
    "tpl_render": {
      "count": 2438,
      "total_ms": 5044.4904,
      "mean_us": 2069.11,
      "max_us": 9239.255
    }
  },
  "measured": {
    "subctx_split": {
      "count": 2436,
      "total_ms": 2.972,
      "mean_us": 1.22,
      "max_us": 4.527
    },
    "tpl_render": {
      "count": 2435,
      "total_ms": 5043.5942,
      "mean_us": 2071.291,
      "max_us": 9239.255
    }
  }
}